version: '3.8'

services:
  C1:
    container_name: C1
    image: ubuntu-16.10
    command: /bin/bash -c "while true; do sleep 3600; done"

  C2:
    container_name: C2
    image: ubuntu-18.10
    command: /bin/bash -c "while true; do sleep 3600; done"

  C3:
    container_name: C3
    image: ubuntu-20.10
    command: /bin/bash -c "while true; do sleep 3600; done"

  C4:
    container_name: S1
    image: ubuntu-22.10
    command: /bin/bash -c "while true; do sleep 3600; done"
